### ISSUE TITLE
Accept JSON

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/drupal-7-module-indicia-api#9]
Accept record model/submodels in JSON format and not in a destructured **smpAttr:**, **occAttr:**, **sc:** key value pairs (form-data)

This should _closely_ resemble warehouse data services [submission format.
](http://indicia-docs.readthedocs.io/en/latest/developing/web-services/submission-format.html)

This would need to support two-step image-record submission.

Differences from existing warehouse data submission fromat:
no **website_id** needed as this would be attached in the module.
**type** would be the model's type - Occurrence or Sample

```JSON
{
  "id": "<set if updating existing>",
  "type": "sample",
  "fields": {
    "survey_id": { "value": "1" },
    "entered_sref": { "value": "SP41" },
    "entered_sref_system": { "value": "OSGB" },
    "date": { "value": "2013-06-13" },
    "comment": { "value": "This is an example record" },
    "smpAttr:3": { "value": "158" },
    "smpAttr:41": { "value": "" },
    "input_form": { "value": "node\/69" }
  },
  "subModels": [
    {
      "id": "<set if updating existing>",
      "type": "sample",
      "fields": {
        "survey_id": { "value": "1" },
        "entered_sref": { "value": "SP4123" },
        "entered_sref_system": { "value": "OSGB" },
        "date": { "value": "2013-06-13" },
        "comment": { "value": "This is an example record" },
      },
      "subModels": [
        {
          "id": "<set if updating existing>",
          "type": "occurrence",
          "fields": {
            "zero_abundance": { "value": "f" },
            "taxa_taxon_list_id": { "value": "30" },
            "record_status": { "value": "C" }
          }
        }
      ]
    }
  ]
}
```

**Comment by japonicus** [comment]
Might it be cleaner to nest the objects hierarchically, doing away with the type attribute, and making the relationship between samples and occurrences more clear.

What's the reason for the {"value" : ... } wrapper?

```
{
  "samples": [
   {
      "id": "<set if updating existing>",
      "survey_id": "1",
      "entered_sref": "SP41",
      "entered_sref_system": "OSGB",
      "date": "2013-06-13",
      "comment": "This is an example record",
      "smpAttrs: {
         "3": "158",
         "41": "",
         }
      "input_form": "node\/69",
      "occurrences": [
         {   
            "id": "<set if updating existing>",
            "zero_abundance": "f",
            "taxa_taxon_list_id": "30",
            "record_status": "C",
            "images" : [
      		]
         } ...
      ],
      "images" : [
      ]
      "samples": [
         {
            "id": "<set if updating existing>",
            "survey_id": "1",
            "entered_sref": "SP4123",
            "entered_sref_system": "OSGB",
            "date": "2013-06-13",
            "comment": "This is an example record",
            "occurrences": [
               {
                  "id": "<set if updating existing>",
                  "zero_abundance": "f",
                  "taxa_taxon_list_id": "30",
                  "record_status": "C"
               } ...
            ]
         } ...
      ]
   } ...
  ]
}
```

**edited to add 'images' per our discussion**

**Comment by kazlauskis** [comment]
Thanks, the **value** wrapper is for unsetting/updating existing values

**Comment by kazlauskis** [comment]
I like this structure, that was more or less what I am supporting at the moment, I think I will split the occurrence and sample subsamples to different lists so it will move from this:
```JSON
{
  "id": "<set if updating existing>",
  "fields": {},
  "subModels": [
    {}, {}, {}, {}, {}, {}
  ]
}
```
**to this:**
```JSON
{
  "id": "<set if updating existing>",
  "fields": {},
  "media": [ {}, {} ],
  "samples": [ {}, {} ],
  "occurrences": [ {}, {} ]
}
```

**media + samples + occurrences** will be merged as **subModels** on a submission to the existing warehouse services, but I think keeping the structure like this will make it a bit cleaner.

**Comment by kazlauskis** [comment]
Hi @andrewvanbreda, I have heard that NPMS allows recording subsamples and occurrences within a sample, is that correct?

So that you would have a square with patches (subsamples) against which you record your plant occurrences, BUT then you can also record occurrences directly within that parent sample, yeah?

Thanks!

**Comment by andrewvanbreda** [comment]
Hi Karolis,

NPMS is actually much simpler than this. It is simply a normal sample with occurrences. The sample holds a plot as a normal location using the location_id field on the sample. The only complication in this regard is that indeed plots have a parent location (square) but this not saved directly against the sample, we just simply look up the parent_id of the plot location if we what to know its square.
So it is actually much simpler than you suggest in general.
However there is an exception to this general rule. There is an additional "Extra Species" page which is not really part of the main scheme, which the user can use to select any plot or square they have permission for as the location for the sample. So these samples could point to a square or plot location.
If you have been looking directly in the database it is this extra complication that might of confused you.
This again is a straightforward situation, it is just that the sample's location_id can point to either a plot or square location.
Hope this helps. Let me know if my explanation is confusing

**Comment by johnvanbreda** [comment]
I'm a bit concerned to see a new "submission format" appearing without thinking about how this fits in with other modules (the REST API and data services for example).

- It seems a shame to propose improvements to the existing submission format without the improved version being made available for posting to data services on the warehouse. This would of course make the mobile auth module simpler because it can (more or less) act as a simple proxy.
- Otherwise you have 2 different formats to learn within the Indicia ecosystem.
- We need to consider how this ties in with the REST API module (which currently is only used as a means to expose occurrences for the purposes of syncing with other databases). This could be updated to accept POSTs of this new format. The REST API module was designed in conjunction with BTO and @japonicus to be platform independent so we'd need to change field names a bit and consider how to handle samples.

I'm not arguing against this development, I just think it warrants a wider discussion about the data submission format with the intention of getting a standard working nicely throughout the platform.

**Comment by kazlauskis** [comment]
Hi, yes I agree with you. Ideally, I should have started working on the warehouse API directly, but since I have very little time dedicated to infrastructure improvements and I would like to have the module up and running by the end of this week, it was much quicker for me to work on the module directly.

Initially, I was planning to use the warehouse's data format, so less documentation and formats to learn. But over the last few weeks while I am working on it I found I can improve it further to fit [JSON API ](http://jsonapi.org/format/) specification better. I am hoping this new format will be accepted by you and others and at some point implemented on the warehouse's REST API side. So that the module will drop its logic and become a mere proxy while retaining its new submission format and existing clients.

@johnvanbreda, @JimBacon, @DavidRoy, @BirenRathod, @andrewvanbreda, @japonicus 
**Let me know if you would like to see different [warehouse's submission format](http://indicia-docs.readthedocs.io/en/latest/developing/web-services/submission-format.html?highlight=sample%3Adate) changes** than the ones I have proposed here now. The main changes I would like to see are:

1. **id** field used for updating existing model only
2. **type** field dropped (maybe media would still require - image/video/audio)
3. **subModules** split into three categories: 
```JSON
{
  "media": [ {}, {} ],
  "samples": [ {}, {} ],
  "occurrences": [ {}, {} ]
}
```
4. dropping **value wrapper** and using **value:**_null_ instead 
5. using **numbers for custom attributes** eg. smpAttr/occAttr
```JSON
{
  "fields": { 
     "date": "12/12/2016", 
     "1234": null
   },
}
```
6. **website_id** would only be needed once, at the parent sample
7. dropping model double wrapper
```JSON
{
   "subModels": [
       {
          "fkId": "sample_id",
          "model": {
              "id": 1234
           }
       }
   ]
}
```
would become:
```JSON
{
   "occurrences": [
      {
        "id": 1234
      }
   ]
}
```

**Comment by japonicus** [comment]
@johnvanbreda, I agree with you that a proliferation of different json formats to describe Indicia data is not desirable.  Had I read Karolis' opening post in this issue more carefully and realised (as he stated explicitly!) that the format he was proposing for the mobile api matched a pre-existing Warehouse json serialisation rather than being a new invention for the mobile api then I would have been more reticent about suggesting structural changes.

That said, I think there may be a case for revising the warehouse json serialisation format and perhaps then adopting it universally for data exchange.  There are still problems with the [Indicia/BTO/BSBI exchange format](http://indicia-online-recording-rest-api.readthedocs.io/en/latest/resources/taxon-observation.html).  It's a good fit for BTO's use-case, where they want transfer of quite minimal records, whereas for the BSBI, a format that included a far broader attribute set and support for images is really needed. That need may brings our requirements much closer to the bare warehouse format than is optimal for BTO. 

Although the BSBI's database doesn't currently support any concept of grouping of occurrences as a sample or survey, I think it's likely that we will move toward support for that, and it would be useful for the exchange format to allow for that possibility. The warehouse or proposed mobile format does that easily, but the sample structure is not supported in the BTO exchange format.

The inclusion of dataset metadata etc in the BTO format is useful and would be harder (or less concise) to express using the native warehouse submission format.

Notwithstanding Karolis' need to have the mobile api specification 'fixed' quickly I think that any changes to the warehouse serialization format need careful consideration (so that there might be scope to adopt a single common format). I would also like to get Indicia-BSBI data exchange finalised and in place soon (am well aware that many of the delays are at my end). There is considerable demand from our county recorders for this.

**Comment by kazlauskis** [comment]
Thanks @japonicus. I am happy to make changes to my proposed improvements. On the other hand, I would rather use the existing warehouse' format if otherwise I would have to wait months to have a settled Indicia-BTO-BSBI format specification.

**Comment by johnvanbreda** [comment]
@kazlauskis if you implement an imperfect format this week to meet deadlines, what are the implications if we then take the time to review your changes against the serialisation formation implemented in the warehouse data services and come up with an improved common standard that can be used across the board? Will you then have difficulties rolling out the update to your app and the Drupal module, or do you think this can be handled by versioning?
I ask because I think attempting to do this properly this week is going to be tricky.

**Comment by kazlauskis** [comment]
Yes, the versioning should cover the future changes. I wouldn't worry too much of breaking the API though of course, it would be great to have it started on the right track.
